#ifndef _TYPES_H_
#define _TYPES_H_

#include <stddef.h>

#if defined(_WIN32)
#include <windows.h>
#include <stdint.h>

// We don't give a rip about unused formal parameters or anonymous unions.
// We're also squelching "conditional is constant" since there are so many
// of them in 3rd party libraries that are valid usages.
#pragma warning(disable:4100)
#pragma warning(disable:4201)
#pragma warning(disable:4127)
#pragma warning(disable:4131)

// Windows silliness
#define	snprintf	_snprintf

#ifndef REAL32
typedef float					REAL32;
#endif // REAL32

#ifndef REAL64
typedef double					REAL64;
#endif // REAL64

#ifndef REAL
typedef double					REAL;
#endif // REAL

#define	real32_t	REAL32
#define	real64_t	REAL64
#define	real_t		REAL

#define	bool_t		bool

#ifndef M_PI
#define	M_PI	3.14159265358979323846
#endif

// stdint equivalents
typedef UINT8 uint8_t;
typedef UINT16 uint16_t;
typedef UINT32 uint32_t;
typedef UINT64 uint64_t;
typedef INT8 int8_t;
typedef INT16 int16_t;
typedef INT32 int32_t;
typedef INT64 int64_t;

typedef char bool;
#define false 0
#define true 1

#elif defined(_IAR) || defined(__linux__) || defined(__FREEBSD__)

#include <stdbool.h>
#include <stdint.h>

#ifndef NO_STDINT_REDEFINE
// Mapping stdint-style typedefs to our native type
#define	uint8_t		uint8_t
#define	uint16_t	uint16_t
#define	uint32_t	uint32_t
#define	uint64_t	uint64_t
#define	int8_t		int8_t
#define	int16_t		int16_t
#define	int32_t		int32_t
#define	int64_t		int64_t
#endif

#define	real32_t	REAL32
#define	real64_t	REAL64
#define	real_t		REAL

#define	bool_t		bool

#include <string.h>

#else
#error "Architecture not defined in types.h"
#endif


// Packing defines
#if defined(_IAR)

#define PACKED_BEGIN
#define PACKED_STRUCT_START        __packed
#define PACKED_STRUCT
#define PACKED_STRUCT_STOP
#define PACKED_END 

#elif defined(_UNIX)

//#define PACKED_BEGIN			_Pragma("pack(1)")
#define PACKED_BEGIN
#define PACKED_STRUCT_START
#define PACKED_STRUCT			__attribute__((packed))
#define PACKED_STRUCT_STOP
//#define PACKED_END				_Pragma("options align=reset")
#define PACKED_END
//#define	__packed

#elif defined(_WIN32) || defined(_WIN64)

#define PACKED_BEGIN				__pragma(pack(push, 1))
#define PACKED_STRUCT_START        
#define PACKED_STRUCT
#define PACKED_STRUCT_STOP
#define PACKED_END					__pragma(pack(pop))

#else
#error "Platform not defined in types.h (for structure packing)"
#endif

#ifndef MIN
#define MIN(a, b)  (((a) < (b)) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a, b)  (((a) > (b)) ? (a) : (b))
#endif

// Unicode character type
typedef uint32_t EUnicode;

// Network protocols
typedef enum
{
	ENETPROTOCOL_UNSPECIFIED,
	ENETPROTOCOL_IPV4,
	ENETPROTOCOL_IPV6
} ENetworkProtocol;

// Error codes
typedef enum
{
	ESTATUS_OK=0,

	// Filesystem errors - THESE MUST BE IN THE SAME ORDER AS ARE IN ff.h AND START +1 FROM ESTATUS_OK!
	ESTATUS_DISK_ERR,				/* (1) A hard error occurred in the low level disk I/O layer */
	ESTATUS_INT_ERR,				/* (2) Assertion failed */
	ESTATUS_NOT_READY,				/* (3) The physical drive cannot work */
	ESTATUS_NO_FILE,				/* (4) Could not find the file */
	ESTATUS_NO_PATH,				/* (5) Could not find the path */
	ESTATUS_INVALID_NAME,			/* (6) The path name format is invalid */
	ESTATUS_DENIED,					/* (7) Access denied due to prohibited access or directory full */
	ESTATUS_EXIST,					/* (8) Access denied due to prohibited access */
	ESTATUS_INVALID_OBJECT,			/* (9) The file/directory object is invalid */
	ESTATUS_WRITE_PROTECTED,		/* (10) The physical drive is write protected */
	ESTATUS_INVALID_DRIVE,			/* (11) The logical drive number is invalid */
	ESTATUS_NOT_ENABLED,			/* (12) The volume has no work area */
	ESTATUS_NO_FILESYSTEM,			/* (13) There is no valid FAT volume */
	ESTATUS_MKFS_ABORTED,			/* (14) The f_mkfs() aborted due to any parameter error */
	ESTATUS_TIMEOUT,				/* (15) Could not get a grant to access the volume within defined period */
	ESTATUS_LOCKED,					/* (16) The operation is rejected according to the file sharing policy */
	ESTATUS_NOT_ENOUGH_CORE,		/* (17) LFN working buffer could not be allocated */
	ESTATUS_TOO_MANY_OPEN_FILES,	/* (18) Number of open files > _FS_LOCK */
	ESTATUS_INVALID_PARAMETER,		/* (19) Given parameter is invalid */
	ESTATUS_INVALID_FILE_MODE,		// Open mode passed to fopen() is unknown/invalid
	ESTATUS_SEEK_ORIGIN_INVALID,	// BIOSfseek Origin is bogus
	ESTATUS_FILE_INVALID_ATTRIBUTES, // Invalid file attributes
	ESTATUS_FILEFIND_ALREADY_ALLOCATED,	// FileFind structure already created
	ESTATUS_UNKNOWN_FRESULT,		// No idea what this FRESULT is
	ESTATUS_FUNCTION_NOT_SUPPORTED,	// Function isn't supported
	ESTATUS_READ_TRUNCATED,			// Read has been truncated
	ESTATUS_WRITE_TRUNCATED,		// Write has been truncated
	ESTATUS_INVALID_CRYPT_MODE,		// Attempt to read while writing (or vice versa) an encrypted file
	ESTATUS_FILE_HANDLE_INVALID,	// File handle is bad
	ESTATUS_DISK_FULL,				// Disk full
	ESTATUS_FILE_FULL,				// File too large for filesystem
	ESTATUS_DATA_MISCOMPARE,		// Data miscompare issue
	// End filesystem errors

	// Heap manager errors
	ESTATUS_OUT_OF_MEMORY=200,

	// Serial port errors
	ESTATUS_SERIAL_INVALID_HANDLE=400,
	ESTATUS_SERIAL_CONSUMER_SLOTS_FULL,
	ESTATUS_SERIAL_CONSUMER_NOT_FOUND,
	ESTATUS_SERIAL_NOT_CONNECTED,
	ESTATUS_SERIAL_SET_BAUDRATE_INVALID,
	ESTATUS_SERIAL_FLUSH_FAULT,
	ESTATUS_SERIAL_WRITE_EVENT_FAILED,
	ESTATUS_SERIAL_WAIT_FAULT,
	ESTATUS_SERIAL_SETUP_INIT_FAILED,

	// OS Errors
	ESTATUS_OS_NOT_RUNNING=500,
	ESTATUS_OS_NOT_ALLOWED_FROM_ISR,
	ESTATUS_OS_SEMAPHORE_GET_FAILED,
	ESTATUS_OS_UNKNOWN_ERROR,
	ESTATUS_OS_SEMAPHORE_CANT_PUT,
	ESTATUS_OS_SEMAPHORE_PUT_COUNT_NOT_SUPPORTED,
	ESTATUS_OS_QUEUE_CANT_CLEAR,
	ESTATUS_OS_THREAD_PRIORITY_INVALID,
	ESTATUS_OS_ISR_CANNOT_BLOCK,
	ESTATUS_OS_SEMAPHORE_UNAVAILABLE,
	ESTATUS_OS_EVENT_FLAG_DELETED,
	ESTATUS_OS_CRITICAL_SECTION_CANT_CREATE,
	ESTATUS_OS_CRITICAL_SECTION_ATTRIBUTE_FAULT,
	ESTATUS_OS_SEMAPHORE_CANT_CREATE,
	ESTATUS_OS_THREAD_CANT_CREATE,
	ESTATUS_OS_QUEUE_FULL,
	ESTATUS_OS_QUEUE_OVERFLOW,
	ESTATUS_OS_THREAD_DESTROY_FAILURE,
	ESTATUS_OS_SEMAPHORE_CANT_DESTROY,
	ESTATUS_OS_NETWORK_INIT_FAILURE,
	ESTATUS_OS_END_OF_FILE,

	// Ernnos
	ESTATUS_ERRNO_OPERATION_NOT_PERMITTED = 600,
	ESTATUS_ERRNO_BASE = ESTATUS_ERRNO_OPERATION_NOT_PERMITTED,
	ESTATUS_ERRNO_NO_SUCH_PROCESS,
	ESTATUS_ERRNO_INTERRUPTED_SYSTEM_CALL,
	ESTATUS_ERRNO_IO_ERROR,
	ESTATUS_ERRNO_DEVICE_NOT_CONFIGURED,
	ESTATUS_ERRNO_ARGUMENT_LIST_TOO_LONG,
	ESTATUS_ERRNO_EXEC_FORMAT_ERROR,
	ESTATUS_ERRNO_BAD_FILE_DESCRIPTOR,
	ESTATUS_ERRNO_NO_CHILD_PROCESSES,
	ESTATUS_ERRNO_RESOURCE_DEADLOCK_AVOIDED,
	ESTATUS_ERRNO_PERMISSION_DENIED,
	ESTATUS_ERRNO_BAD_ADDRESS,
	ESTATUS_ERRNO_BLOCK_DEVICE_REQUIRED,
	ESTATUS_ERRNO_DEVICE_BUSY,
	ESTATUS_ERRNO_CROSS_DEVICE_LINK,
	ESTATUS_ERRNO_OPERATION_NOT_SUPPORTED,
	ESTATUS_ERRNO_NOT_A_DIRECTORY,
	ESTATUS_ERRNO_IS_A_DIRECTORY,
	ESTATUS_ERRNO_INAPPROPRIATE_IOCTL,
	ESTATUS_ERRNO_TEXT_FILE_BUSY,
	ESTATUS_ERRNO_FILE_TOO_LARGE,
	ESTATUS_ERRNO_NO_SPACE_LEFT_ON_DEVICE,
	ESTATUS_ERRNO_ILLEGAL_SEEK,
	ESTATUS_ERRNO_READ_ONLY_FILESYSTEM,
	ESTATUS_ERRNO_TOO_MANY_LINKS,
	ESTATUS_ERRNO_BROKEN_PIPE,
	ESTATUS_ERRNO_NUMERICAL_ARGUMENT_OUT_OF_DOMAIN,
	ESTATUS_ERRNO_RESULTS_TOO_LARGE,
	ESTATUS_ERRNO_RESOURCE_TEMPORARILY_UNAVAILABLE,
	ESTATUS_ERRNO_OPERATION_IN_PROGRESS,
	ESTATUS_ERRNO_OPERATION_ALREADY_IN_PROGRESS,
	ESTATUS_ERRNO_SOCKET_OP_ON_NON_SOCKET,
	ESTATUS_ERRNO_DESTIONATION_ADDRESS_REQUIRED,
	ESTATUS_ERRNO_MESSAGE_TOO_LONG,
	ESTATUS_ERRNO_PROTOCOL_WRONG_TYPE_FOR_SOCKET,
	ESTATUS_ERRNO_PROTOCOL_NOT_AVAILABLE,
	ESTATUS_ERRNO_PROTOCOL_NOT_SUPPORTED,
	ESTATUS_ERRNO_SOCKET_TYPE_NOT_SUPPORTED,
	ESTATUS_ERRNO_PROTOCOL_FAMILY_NOT_SUPPROTED,
	ESTATUS_ERRNO_ADDRESS_FAMILY_NOT_SUPPORTED,
	ESTATUS_ERRNO_ADDRESS_ALREADY_IN_USE,
	ESTATUS_ERRNO_CANT_ASSIGN_REQUESTED_ADDRESS,
	ESTATUS_ERRNO_NETWORK_IS_DOWN,
	ESTATUS_ERRNO_NETWORK_UNREACHABLE,
	ESTATUS_ERRNO_NETWORK_DROPPED_CONNECTION_ON_RESET,
	ESTATUS_ERRNO_SOFTWARE_CAUSED_CONNECTIONABORT,	
	ESTATUS_ERRNO_CONNECTION_RESET_BY_PEER,
	ESTATUS_ERRNO_NO_BUFFER_SPACE_AVAILABLE,
	ESTATUS_ERRNO_SOCKET_ALREADY_CONNECTED,
	ESTATUS_ERRNO_SOCKET_NOT_CONNECTED,
	ESTATUS_ERRNO_CANT_SENT_SOCKET_SHUTDOWN,
	ESTATUS_ERRNO_TOO_MANY_REFERENCES_CANT_SPLICE,
	ESTATUS_ERRNO_CONNECTION_REFUSED,
	ESTATUS_ERRNO_TOO_MANY_LEVELS_OF_SYMBOLIC_LINKS,
	ESTATUS_ERRNO_FILENAME_TOO_LONG,
	ESTATUS_ERRNO_HOST_IS_DOWN,
	ESTATUS_ERRNO_NO_ROUTE_TO_HOST,
	ESTATUS_ERRNO_DIRECTORY_NOT_EMPTY,
	ESTATUS_ERRNO_TOO_MANY_PROCESSES,
	ESTATUS_ERRNO_TOO_MANY_USERS,
	ESTATUS_ERRNO_DISK_QUOTA_EXCEEDED,
	ESTATUS_ERRNO_STALE_NFS_FILE_HANDLE,
	ESTATUS_ERRNO_TOO_MANY_LEVELS_OF_REMOTE_IN_PATH,
	ESTATUS_ERRNO_RPC_STRUCT_IS_BAD,
	ESTATUS_ERRNO_RPC_VERSION_WRONG,
	ESTATUS_ERRNO_RPC_PROGRAM_NOT_AVAILABLE,
	ESTATUS_ERRNO_PROGRAM_VERSION_WRONG,
	ESTATUS_ERRNO_BAD_PROCEDURE_FOR_PROGRAM,
	ESTATUS_ERRNO_NO_LOCKS_AVAILABLE,
	ESTATUS_ERRNO_INAPPROPRIATE_FILE_TYPE_OR_FORMAT,
	ESTATUS_ERRNO_AUTHENTICATION_ERROR,
	ESTATUS_ERRNO_NEED_AUTHENTICATOR,
	ESTATUS_ERRNO_IDENTIFIER_REMOVED,
	ESTATUS_ERRNO_NO_MSG_OF_DESIRED_TYPE,
	ESTATUS_ERRNO_VALUE_TOO_LARGE_TO_BE_STORED,
	ESTATUS_ERRNO_OPERATION_CANCELED,
	ESTATUS_ERRNO_ILLEGAL_BYTE_SEQUENCE,
	ESTATUS_ERRNO_ATTRIBUTE_NOT_FOUND,
	ESTATUS_ERRNO_PROGRAMMING_ERROR,
	ESTATUS_ERRNO_BAD_MESSAGE,
	ESTATUS_ERRNO_MUTLIHOP_ATTEMPTED,
	ESTATUS_ERRNO_LINK_HAS_BEEN_SEVERED,
	ESTATUS_ERRNO_PROTOCOL_ERROR,
	ESTATUS_ERRNO_CAPABILITIES_INSUFFICIENT,
	ESTATUS_ERRNO_NOT_PERMITTED_IN_CAPABILITY_MODE,
	ESTATUS_ERRNO_STATE_NOT_RECOVERABLE,
	ESTATUS_ERRNO_PREVIOUS_OWNER_DIED,
	ESTATUS_ERRNO_MUST_BE_EQUAL_LARGEST_ERRNO,
	ESTATUS_ERRNO_RESTART_SYSCALL,
	ESTATUS_ERRNO_DONT_MODIFY_REGS,
	ESTATUS_ERRNO_IOCTL_NOT_HANDLED_BY_THIS_LAYER,
	ESTATUS_ERRNO_DO_DIRECT_IOCTL_IN_GEOM,
	ESTATUS_FILE_ERROR_PENDING,
	ESTATUS_ERRNO_EDEADLK,
	ESTATUS_ERRNO_ENAMETOOLONG,
	ESTATUS_ERRNO_ENOLCK,
	ESTATUS_ERRNO_ENOSYS,
	ESTATUS_ERRNO_ENOTEMPTY,
	ESTATUS_ERRNO_ELOOP,
	ESTATUS_ERRNO_EWOULDBLOCK,
	ESTATUS_ERRNO_ENOMSG,
	ESTATUS_ERRNO_EIDRM,
	ESTATUS_ERRNO_ECHRNG,
	ESTATUS_ERRNO_EL2NSYNC,
	ESTATUS_ERRNO_EL3HLT,
	ESTATUS_ERRNO_EL3RST,
	ESTATUS_ERRNO_ELNRNG,
	ESTATUS_ERRNO_EUNATCH,
	ESTATUS_ERRNO_ENOCSI,
	ESTATUS_ERRNO_EL2HLT,
	ESTATUS_ERRNO_EBADE,
	ESTATUS_ERRNO_EBADR,
	ESTATUS_ERRNO_EXFULL,
	ESTATUS_ERRNO_ENOANO,
	ESTATUS_ERRNO_EBADRQC,
	ESTATUS_ERRNO_EBADSLT,
	ESTATUS_ERRNO_EDEADLOCK,
	ESTATUS_ERRNO_EBFONT,
	ESTATUS_ERRNO_ENOSTR,
	ESTATUS_ERRNO_ENODATA,
	ESTATUS_ERRNO_ETIME,
	ESTATUS_ERRNO_ENOSR,
	ESTATUS_ERRNO_ENONET,
	ESTATUS_ERRNO_ENOPKG,
	ESTATUS_ERRNO_EREMOTE,
	ESTATUS_ERRNO_ENOLINK,
	ESTATUS_ERRNO_EADV,
	ESTATUS_ERRNO_ESRMNT,
	ESTATUS_ERRNO_ECOMM,
	ESTATUS_ERRNO_EPROTO,
	ESTATUS_ERRNO_EMULTIHOP,
	ESTATUS_ERRNO_EDOTDOT,
	ESTATUS_ERRNO_EBADMSG,
	ESTATUS_ERRNO_EOVERFLOW,
	ESTATUS_ERRNO_ENOTUNIQ,
	ESTATUS_ERRNO_EBADFD,
	ESTATUS_ERRNO_EREMCHG,
	ESTATUS_ERRNO_ELIBACC,
	ESTATUS_ERRNO_ELIBBAD,
	ESTATUS_ERRNO_ELIBSCN,
	ESTATUS_ERRNO_ELIBMAX,
	ESTATUS_ERRNO_ELIBEXEC,
	ESTATUS_ERRNO_EILSEQ,
	ESTATUS_ERRNO_ERESTART,
	ESTATUS_ERRNO_ESTRPIPE,
	ESTATUS_ERRNO_EUSERS,
	ESTATUS_ERRNO_ENOTSOCK,
	ESTATUS_ERRNO_EDESTADDRREQ,
	ESTATUS_ERRNO_EMSGSIZE,
	ESTATUS_ERRNO_EPROTOTYPE,
	ESTATUS_ERRNO_ENOPROTOOPT,
	ESTATUS_ERRNO_EPROTONOSUPPORT,
	ESTATUS_ERRNO_ESOCKTNOSUPPORT,
	ESTATUS_ERRNO_EOPNOTSUPP,
	ESTATUS_ERRNO_EPFNOSUPPORT,
	ESTATUS_ERRNO_EAFNOSUPPORT,
	ESTATUS_ERRNO_EADDRINUSE,
	ESTATUS_ERRNO_EADDRNOTAVAIL,
	ESTATUS_ERRNO_ENETDOWN,
	ESTATUS_ERRNO_ENETUNREACH,
	ESTATUS_ERRNO_ENETRESET,
	ESTATUS_ERRNO_ECONNABORTED,
	ESTATUS_ERRNO_ECONNRESET,
	ESTATUS_ERRNO_ENOBUFS,
	ESTATUS_ERRNO_EISCONN,
	ESTATUS_ERRNO_ENOTCONN,
	ESTATUS_ERRNO_ESHUTDOWN,
	ESTATUS_ERRNO_ETOOMANYREFS,
	ESTATUS_ERRNO_ETIMEDOUT,
	ESTATUS_ERRNO_ECONNREFUSED,
	ESTATUS_ERRNO_EHOSTDOWN,
	ESTATUS_ERRNO_EHOSTUNREACH,
	ESTATUS_ERRNO_EALREADY,
	ESTATUS_ERRNO_EINPROGRESS,
	ESTATUS_ERRNO_ESTALE,
	ESTATUS_ERRNO_EUCLEAN,
	ESTATUS_ERRNO_ENOTNAM,
	ESTATUS_ERRNO_ENAVAIL,
	ESTATUS_ERRNO_EISNAM,
	ESTATUS_ERRNO_EREMOTEIO,
	ESTATUS_ERRNO_EDQUOT,
	ESTATUS_ERRNO_ENOMEDIUM,
	ESTATUS_ERRNO_EMEDIUMTYPE,
	ESTATUS_ERRNO_ECANCELED,
	ESTATUS_ERRNO_ENOKEY,
	ESTATUS_ERRNO_EKEYEXPIRED,
	ESTATUS_ERRNO_EKEYREVOKED,
	ESTATUS_ERRNO_EKEYREJECTED,
	ESTATUS_ERRNO_EOWNERDEAD,
	ESTATUS_ERRNO_ENOTRECOVERABLE,
	ESTATUS_ERRNO_ERFKILL,
	ESTATUS_ERRNO_EHWPOISON,
	ESTATUS_ERRNO_STRUNCATE,
	ESTATUS_ERRNO_UNKNOWN,

	// ZLib errors
	ESTATUS_ZIP_FILE_INTEGRITY_PROBLEM = 1000,
	ESTATUS_ZIP_INTERNAL_ERROR,
	ESTATUS_ZIP_CHECK_CODE_FAILED,
	ESTATUS_ZIP_UNKNOWN_ERROR,
	ESTATUS_ZIP_END_OF_FILE,
	ESTATUS_ZIP_BAD_FILE,
	ESTATUS_ZIP_PROFILE_PIN_INVALID,
	ESTATUS_ZIP_BAD_LOAD_ADDRESS,
	ESTATUS_ZIP_WRITE_TRUNCATED,
	ESTATUS_ZIP_NO_MORE_FILES,
	ESTATUS_ZIP_INVALID_PARAMETER,
	ESTATUS_ZIP_CRC_MISMATCH,
	ESTATUS_ZIP_NEED_DICT,
	ESTATUS_ZIP_ERRNO,
	ESTATUS_ZIP_STREAM_ERROR,
	ESTATUS_ZIP_DATA_ERROR,
	ESTATUS_ZIP_BUFFER_ERROR,
	ESTATUS_ZIP_VERSION_ERROR,

	// Syslog errors
	ESTATUS_SYSLOG_NOT_INITIALIZED = 1100,
	ESTATUS_SYSLOG_NOT_FROM_ISR,
	ESTATUS_SYSLOG_DATA_TRUNCATED,

	// Cipher errors
	ESTATUS_CIPHER_INIT_FAILURE = 1200,
	ESTATUS_CIPHER_DECRYPTION_FAULT,
	ESTATUS_CIPHER_ENCRYPTION_FAULT,

	// Misc administrative errors
	ESTATUS_LOGGED_ASSERT_UNAVAILABLE=1300,
	ESTATUS_LANGUAGE_NOT_AVAILABLE,
	ESTATUS_TRANSLATION_NOT_FOUND,
	ESTATUS_LINE_TOO_LONG,

	// UtilTask errors
	ESTATUS_UTILTASK_KEY_IN_USE = 1400,
	ESTATUS_UTILTASK_KEY_NOT_FOUND,

	// SysEvent errors
	ESTATUS_SYSEVENT_MISSING_SIGNAL = 1500,

	// Parse errors
	ESTATUS_PARSE_NUMERIC_VALUE_EXPECTED = 1600,
	ESTATUS_PARSE_EQUALS_EXPECTED,
	ESTATUS_PARSE_SEMICOLON_EXPECTED,
	ESTATUS_PARSE_STRING_EXPECTED,
	ESTATUS_PARSE_COMMA_EXPECTED,
	ESTATUS_PARSE_UINT_EXPECTED,
	ESTATUS_PARSE_INT_EXPECTED,
	ESTATUS_PARSE_UINT8_EXPECTED,
	ESTATUS_PARSE_INT8_EXPECTED,
	ESTATUS_PARSE_UINT16_EXPECTED,
	ESTATUS_PARSE_INT16_EXPECTED,
	ESTATUS_PARSE_UINT32_EXPECTED,
	ESTATUS_PARSE_INT32_EXPECTED,
	ESTATUS_PARSE_UINT64_EXPECTED,
	ESTATUS_PARSE_INT64_EXPECTED,
	ESTATUS_PARSE_FLOAT_EXPECTED,
	ESTATUS_PARSE_DOUBLE_EXPECTED,
	ESTATUS_PARSE_VALUE_OUT_OF_RANGE,
	ESTATUS_PARSE_ERROR,

	// Patient errors
	ESTATUS_PATIENT_DUPLICATE_NAME=1700,
	ESTATUS_PATIENT_GENDER_NOT_SET,
	ESTATUS_PATIENT_LOCAL_LOOKUP_FAULT,
	ESTATUS_PATIENT_DATA_UNCHANGED,
	ESTATUS_PATIENT_CLINIC_SELECT_REQUIRED,
	ESTATUS_PATIENT_ATTENDING_DOCTOR_MISSING,
	ESTATUS_PATIENT_NOT_FOUND,
	ESTATUS_PATIENT_MISSING,
	ESTATUS_PATIENT_ADD_UPDATE_FAILURE,
	ESTATUS_PATIENT_REFERRED_BY_OTHER_BLANK,

	// Session errors
	ESTATUS_UNKNOWN_COMMAND=1800,
	ESTATUS_SERVER_LIST_UPDATED,
	ESTATUS_DATABASE_ALLOC_FAULT,
	ESTATUS_SERVER_DB_QUERY_FAULT,
	ESTATUS_SERVER_OUT_OF_MEMORY,
	ESTATUS_USERNAME_PASSWORD_BAD,
	ESTATUS_USER_PERMISSIONS_FAULT,
	ESTATUS_SESSION_ID_INVALID,
	ESTATUS_ATOM_SEQUENCE_FAULT,
	ESTATUS_SESSION_NOT_FOUND,
	ESTATUS_SERVER_DB_NO_MORE_DATA,
	ESTATUS_SERVER_DB_DATA_TRUNCATED,
	ESTATUS_SERVER_LIST_INVALID_INDEX,
	ESTATUS_SESSION_FULL,
	ESTATUS_SERVER_IDENTITY_UNKNOWN,
	ESTATUS_SERVER_IDENTITY_MISSING,
	ESTATUS_KEY_INDEX_OUT_OF_RANGE,
	ESTATUS_SESSION_NOT_PARENT,
	ESTATUS_SESSION_CHILD_ALREADY_ASSIGNED,
	ESTATUS_DB_STATEMENT_PREPARE_FAILED,
	ESTATUS_DB_BIND_PARAM_FAILED,
	ESTATUS_DB_STATEMENT_EXEC_ERROR,
	ESTATUS_DB_BIND_RESULT_FAILURE,
	ESTATUS_DB_STATEMENT_FETCH_FAILED,
	ESTATUS_DB_FETCH_COLUMN_FAILURE,
	ESTATUS_DB_DUPLICATE,
	ESTATUS_DB_HANDLE_INVALID,
	ESTATUS_SERVER_GROUP_UNKNOWN,
	ESTATUS_SERVER_GROUP_NOT_SET,

	// Clinic errors
	ESTATUS_CLINIC_NAME_MISSING=1900,
	ESTATUS_CLINIC_NAME_DUPLICATE,
	ESTATUS_CLINIC_UNCHANGED,
	ESTATUS_CLINIC_DISABLED,
	ESTATUS_CLINIC_GUID_MISSING,
	ESTATUS_CLINIC_USER_NOT_ASSOCIATED,
	ESTATUS_CLINIC_NOT_FOUND,
	ESTATUS_CLINIC_UPDATE_FAILURE,
	ESTATUS_CLINIC_ADD_FAILURE,
	ESTATUS_CLINIC_NOT_ASSOCIATED,
	ESTATUS_CLINIC_ACTIVE_NOT_SET,

	// Treatment errors
	ESTATUS_TREATMENT_BUFFER_TOO_SMALL = 2100,
	ESTATUS_TREATMENT_STATE_INVALID,
	ESTATUS_TREATMENT_INVALID_PARAMETER,
	ESTATUS_TREATMENT_INVALID_EVENT_TYPE,
	ESTATUS_HOST_TIMING_INVALID_STATE,
	ESTATUS_STIM_MAX_DRIVERS_REGISTERED,
	ESTATUS_STIM_FUNCTION_NOT_SUPPORTED,
	ESTATUS_TREATMENT_FAILED_TO_START,
	ESTATUS_TREATMENT_FAILED_TO_PAUSE,
	ESTATUS_TREATMENT_FAILED_TO_RESUME,
	ESTATUS_TREATMENT_FAILED_TO_END,
	ESTATUS_TREATMENT_FAILED_TO_ADD_PERIOD,
	ESTATUS_TREATMENT_ENDED_ON_DEVICE_CHANGE,
	ESTATUS_TREATMENT_INVALID_AMPLITUDE,
	ESTATUS_TREATMENT_MISSING,
	ESTATUS_TREATMENT_JOB_NOT_SUPPORTED,
	ESTATUS_TREATMENT_NO_SEGMENTS,
	ESTATUS_TREATMENT_ADD_FAILURE,
	ESTATUS_TREATMENT_TIMING_LENGTH_INVALID,
	ESTATUS_TREATMENT_AMPLITUDE_TIMING_MISMATCH,
	ESTATUS_TREATMENT_AMPLITUDE_IMBALANCE,
	ESTATUS_TREATMENT_LOCATION_NOT_SPECIFIED,
	ESTATUS_TREATMENT_LOCATION_INVALID,
	ESTATUS_TREATMENT_TYPE_NOT_SPECIFIED,
	ESTATUS_TREATMENT_TYPE_INVALID,
	ESTATUS_TREATMENT_LOG_MISSING,
	ESTATUS_TREATMENT_NOT_FOUND,
	ESTATUS_TREATMENT_LOG_NO_SEGMENTS,
	ESTATUS_TREATMENT_LOG_EVENT_TIME_NOT_SET,
	ESTATUS_TREATMENT_EVENT_INVALID,
	ESTATUS_TREATMENT_EVENT_UNKNOWN,
	ESTATUS_TREATMENT_STIM_TYPE_INVALID,
	ESTATUS_TREATMENT_STIM_TYPE_UNKNOWN,
	ESTATUS_TREATMENT_TRIG_TYPE_INVALID,
	ESTATUS_TREATMENT_TRIG_TYPE_UNKNOWN,
	ESTATUS_TREATMENT_TIMING_METHOD_INVALID,
	ESTATUS_TREATMENT_TIMING_METHOD_UNKNOWN,
	ESTATUS_TREATMENT_MOTOR_THRESHOLD_INVALID,
	ESTATUS_TREATMENT_GOAL_INTENSITY_INVALID,
	ESTATUS_TREATMENT_INTERTRAIN_TOO_SHORT,
	ESTATUS_TREATMENT_TRAIN_TIME_TOO_SHORT,
	ESTATUS_TREATMENT_CENTER_PERIOD_OUT_OF_RANGE,
	ESTATUS_TREATMENT_PERIOD_STANDARD_DEV_OUT_OF_RANGE,
	ESTATUS_TREATMENT_NUM_OF_SD_OUT_OF_RANGE,
	ESTATUS_TREATMENT_LOCATION_TYPE_MISMATCH,
	ESTATUS_TREATMENT_CONFIGURATION_INVALID,
	ESTATUS_TREATMENT_MOTOR_THRESHOLD_UNCHANGED,
	ESTATUS_STIM_AMPLITUDE_SET_FAILED,
	ESTATUS_STIM_ENABLE_FAILED,	
	ESTATUS_STIM_TRIGGER_FAILED,
	ESTATUS_TREATMENT_GEN_INTERNAL_FAULT,
	ESTATUS_STIM_DEVICE_TRAIN_FAILED,
	ESTATUS_TREATMENT_ALREADY_INITIALIZED,
	ESTATUS_TREATMENT_NOT_INITIALIZED,
	ESTATUS_TREATMENT_INIT_IN_PROGRESS,
	ESTATUS_TREATMENT_DUTY_CYCLE_OUT_OF_RANGE,
	ESTATUS_FONT_ID_NOT_FOUND,
	ESTATUS_TREATMENT_START_LOCKED,
	ESTATUS_TREATMENT_INTENSITY_CHANGED_FROM_START,
	ESTATUS_TREATMENT_TRAIN_TOO_LONG_FOR_STIMULATOR,
	ESTATUS_TREATMENT_INTERTRAIN_TOO_SHORT_FOR_STIMULATOR,
	ESTATUS_TREATMENT_AMPLITUDE_ABOVE_MAXIMUM,
	ESTATUS_TREATMENT_FREQUENCY_ABOVE_MAXIMUM,

	// Socket/networking errors
	ESTATUS_SOCKET_MAX_UDP_SOCKETS = 2200,
	ESTATUS_SOCKET_MAX_TCP_SOCKETS,
	ESTATUS_HOST_NAME_LOOKUP_FAILURE,
	ESTATUS_REMOTE_PORT_OUT_OF_RANGE,
	ESTATUS_SOURCE_PORT_NOT_SUPPORTED,
	ESTATUS_SOCKET_NOT_READY,
	ESTATUS_SSL_ALLOC,
	ESTATUS_NO_LINK,
	ESTATUS_SSL_WRITE_FAULT,
	ESTATUS_SSL_CONNECT,
	ESTATUS_CLIENT_REQUESTED_SHUTDOWN,
	ESTATUS_SSL_READ_FAULT,
	ESTATUS_MALFORMED_RESPONSE,
	ESTATUS_MALFORMED_REQUEST,
	ESTATUS_NO_AVAILABLE_SERVERS,
	ESTATUS_LOST_LINK,
	ESTATUS_SOCKET_ERROR,
	ESTATUS_INVALID_SEQUENCE_NUMBER,

	// Misc errors
	ESTATUS_BUFFER_TOO_SMALL = 2300,
	ESTATUS_ATOM_ID_SUBTYPE_UNKOWN,
	ESTATUS_ATOM_DATA_MISCOMPARE,
	ESTATUS_ATOM_ID_UNKNOWN,
	ESTATUS_RANDOM_NUMBER_NOT_VALID,
	ESTATUS_UNKNOWN_TABLE_TYPE,
	ESTATUS_DATE_DAY_INVALID,
	ESTATUS_DATE_MONTH_INVALID,
	ESTATUS_DATE_YEAR_INVALID,
	ESTATUS_TABLE_NOT_SQL,
	ESTATUS_INTERNAL_ERROR,
	ESTATUS_DATA_TOO_SHORT,
	ESTATUS_HASH_ALREADY_PRESENT,
	ESTATUS_EMPTY,
	ESTATUS_ABORTED,
	ESTATUS_UNKNOWN_RESULT_CODE,
	ESTATUS_HANDLE_INVALID,
	ESTATUS_NO_MORE_HANDLE_TYPES,
	ESTATUS_NO_MORE_HANDLES,
	ESTATUS_HANDLE_POOL_INVALID,
	ESTATUS_HANDLE_POOL_MISMATCH,
	ESTATUS_HANDLE_NOT_ALLOCATED,
	ESTATUS_HANDLE_POOL_NO_CRITICAL_SECTION,
	ESTATUS_TRUNCATED,
	ESTATUS_CANCELLED,

	// Connection errors
	ESTATUS_CONNECTION_HANDLE_INVALID=2400,
	ESTATUS_CONNECTION_HANDLES_FULL,
	ESTATUS_CONNECTION_NOT_ALLOCATED,
	ESTATUS_CONNECTION_INVALID_TYPE,
	ESTATUS_CONNECTION_ALREADY_ESTABLISHED,
	ESTATUS_CONNECTION_SERVICE_INVALID,

	// User errors
	ESTATUS_USER_NOT_FOUND=2700,
	ESTATUS_USER_DISABLED,
	ESTATUS_USER_NOT_AUTHORIZER,
	ESTATUS_USER_USERNAME_PRESENT,
	ESTATUS_USER_UPDATE_FAILURE,
	ESTATUS_USER_MALFORMED_PASSWORD,
	ESTATUS_USER_PASSWORD_MISSING,
	ESTATUS_USER_PASSWORD_SET_OTHER,
	ESTATUS_USER_UNCHANGED,
	ESTATUS_USER_PASSWORD_MISMATCH,
	ESTATUS_USER_PASSWORD_BAD_POLICY,
	ESTATUS_USER_PASSWORD_BLANK,
	ESTATUS_USER_PASSWORD_TOO_SHORT,
	ESTATUS_USER_MISSING,
	ESTATUS_USER_CLINIC_ACTIVE_SELECT_REQUIRED,
	ESTATUS_USER_NOT_A_CLINICIAN,

	// Misc system errors
	ESTATUS_GUID_MISSING=2800,
	ESTATUS_INSTANCE_GUID_MISSING,
	ESTATUS_GUID_TYPE_MISMATCH,
	ESTATUS_INSTANCE_GUID_TYPE_MISMATCH,
	ESTATUS_INSTANCE_IN_GUID,
	ESTATUS_GUID_IN_INSTANCE,
	ESTATUS_DATA_MISSING,
	ESTATUS_GUID_NULL_CHECK_FAILED,

	// Field errors (generic)
	ESTATUS_FIELD_ERROR=2900,
	ESTATUS_FIELD_BLANK,
	ESTATUS_FIELD_INVALID,
	ESTATUS_FIELD_COUNTRY_NOT_SPECIFIED,
	ESTATUS_FIELD_COUNTRY_INVALID,
	ESTATUS_FIELD_VALUE_IS_ZERO,
	ESTATUS_FIELD_IS_NULL,
	ESTATUS_FIELD_TOO_LONG,
	ESTATUS_FIELD_MUST_BE_ZERO,
	ESTATUS_FIELD_IS_NOT_NULL,

	// Software update errors
	ESTATUS_UPDATE_FLAGS_UNCHANGED=3000,
	ESTATUE_UPDATE_COMPONENT_MISSING,
	ESTATUS_UPDATE_EXEC_BUILD_ALREADY_EXISTS,
	ESTATUS_UPDATE_WRITE_OR_VERIFY_FAULT,

	// File store errors
	ESTATUS_FILESTORE_FILE_TYPE_UNSPECIFIED=3100,
	ESTATUS_FILESTORE_FILE_TYPE_UNKNOWN,
	ESTATUS_FILESTORE_FILE_ZERO_LENGTH,
	ESTATUS_FILESTORE_FILE_AMBIGUOUS,
	ESTATUS_FILESTORE_FILE_TOO_SMALL_FOR_TYPE,
	ESTATUS_FILESTORE_FILE_UNEXPECTED_FILE_TYPE,
	ESTATUS_FILESTORE_FILE_DUPLICATE,
	ESTATUS_FILESTORE_FILE_USE_NOT_SPECIFIED,
	ESTATUS_FILESTORE_FILE_USE_INVALID,
	ESTATUS_FILESTORE_FILE_ASSESSMENT_USE_INVALID,
	ESTATUS_FILESTORE_FILE_CLASS_UNKNOWN,
	ESTATUS_FILESTORE_FILE_USE_UNKNOWN,
	ESTATUS_FILESTORE_FILE_AUTODETECT_FAILED,

	// Patient Notes errors
	ESTATUS_PATIENTNOTE_FLAGS_NOT_SET=3200,
	ESTATUS_PATIENTNOTE_FLAGS_INVALID,

	// Machine ID errors
	ESTATUS_MACHINE_ID_NOT_FOUND=3300,

	// EEG errors
	ESTATUS_EEG_NOT_AN_EEG_FILE=3400,
	ESTATUS_EEG_FILE_CORRUPT,
	ESTATUS_EEG_FILE_TOO_SMALL,
	ESTATUS_EEG_FILE_INVALID_SAMPLE_RATE,
	ESTATUS_EEG_CHANNEL_NOT_FOUND,
	ESTATUS_EEG_FILE_TYPE_NOT_SUPPORTED,
	ESTATUS_EEG_CHANNEL_OUT_OF_RANGE,
	ESTATUS_EEG_DEVICE_HANDLE_INVALID,
	ESTATUS_EEG_HANDLES_FULL,

	// Service errors
	ESTATUS_SERVICE_HANDLE_INVALID=3500,
	ESTATUS_SERVICE_HANDLES_FULL,
	ESTATUS_SERVICE_NOT_ALLOCATED,
	ESTATUS_SERVICE_NO_MATCHES,

	// Sound errors
	ESTATUS_SOUND_HARDWARE_FAULT=3600,

	// Sample errors
	ESTATUS_RESAMPLE_TYPE_UNKNOWN=3700,
	ESTATUS_ALGORITHM_UNKNOWN,

	// Job errors
	ESTATUS_JOB_PENDING=3800,
	ESTATUS_JOB_ALREADY_IN_PROGRESS,
	ESTATUS_JOB_PROCESSOR_NOT_READY,
	ESTATUS_JOB_INVALID_STATUS,
	ESTATUS_JOB_SETTING_ALREADY_PRESENT,
	ESTATUS_JOB_ADD_FAILURE,
	ESTATUS_JOB_SETTINGS_ADD_FAILURE,
	ESTATUS_JOBS_LANGUAGE_INVALID,
	ESTATUS_JOB_GUID_IS_NULL,
	ESTATUS_JOB_GUID_IS_NOT_NULL,

	// ReportBot errors
	ESTATUS_REPORTBOT_CHANNEL_MISSING=3900,
	ESTATUS_REPORTBOT_STATIC_FILE_MISSING,
	ESTATUS_REPORTBOT_INTERNAL_CALC_ERROR,
	ESTATUS_REPORTBOT_NO_REMAINING_DATA,

	// Report errors
	ESTATUS_REPORT_TYPE_UNKNOWN=4100,

	// Next should be 4200
	ESTATUS_VERSION_TAG_NOT_SPECIFIED=4200,
	ESTATUS_VERSION_TAG_NOT_APPLICABLE,
	ESTATUS_VERSION_TAG_NOT_FOUND,
	ESTATUS_VERSION_BAD_CRC32,
	ESTATUS_VERSION_BAD_HASH,

	// Graphics error codes
	ESTATUS_GFX_INIT_FAULT=4300,
	ESTATUS_GFX_DISPLAY_MODE_FAULT,
	ESTATUS_GFX_FILE_FORMAT_UNKNOWN,
	ESTATUS_GFX_FILE_CORRUPT,
	ESTATUS_GFX_FILE_NOT_SUPPORTED,

	// Freetype error codes
	ESTATUS_FREETYPE_INVALID_ARGUMENT=4400,
	ESTATUS_FREETYPE_CANT_OPEN_RESOURCE,
	ESTATUS_FREETYPE_UNKNOWN_FILE_FORMAT,
	ESTATUS_FREETYPE_INVALID_FILE_FORMAT,
	ESTATUS_FREETYPE_INVALID_VERSION,
	ESTATUS_FREETYPE_LOWER_MODULE_VERSION,
	ESTATUS_FREETYPE_UNIMPLEMENTED_FEATURE,
	ESTATUS_FREETYPE_INVALID_TABLE,
	ESTATUS_FREETYPE_INVALID_OFFSET,
	ESTATUS_FREETYPE_ARRAY_TOO_LARGE,

	ESTATUS_FREETYPE_INVALID_GLYPH_INDEX,
	ESTATUS_FREETYPE_INVALID_CHARACTER_CODE,
	ESTATUS_FREETYPE_INVALID_GLYPH_FORMAT,
	ESTATUS_FREETYPE_CANNOT_RENDER_GLYPH,
	ESTATUS_FREETYPE_INVALID_OUTLINE,
	ESTATUS_FREETYPE_INVALID_COMPOSITE,
	ESTATUS_FREETYPE_TOO_MANY_HINTS,
	ESTATUS_FREETYPE_INVALID_PIXEL_SIZE,

	ESTATUS_FREETYPE_INVALID_HANDLE,
	ESTATUS_FREETYPE_INVALID_LIBRARY_HANDLE,
	ESTATUS_FREETYPE_INVALID_DRIVER_HANDLE,
	ESTATUS_FREETYPE_INVALID_FACE_HANDLE,
	ESTATUS_FREETYPE_INVALID_SIZE_HANDLE,
	ESTATUS_FREETYPE_INVALID_SLOT_HANDLE,
	ESTATUS_FREETYPE_INVALID_CHARMAP_HANDLE,
	ESTATUS_FREETYPE_INVALID_CACHE_HANDLE,
	ESTATUS_FREETYPE_INVALID_STREAM_HANDLE,

	ESTATUS_FREETYPE_TOO_MANY_DRIVERS,
	ESTATUS_FREETYPE_TOO_MANY_EXTENSIONS,

	ESTATUS_FREETYPE_UNLISTED_OBJECT,

	ESTATUS_FREETYPE_CANNOT_OPEN_STREAM,
	ESTATUS_FREETYPE_INVALID_STREAM_SEEK,
	ESTATUS_FREETYPE_INVALID_STREAM_SKIP,
	ESTATUS_FREETYPE_INVALID_STREAM_READ,
	ESTATUS_FREETYPE_INVALID_STREAM_OPERATION,
	ESTATUS_FREETYPE_INVALID_FRAME_OPERATION,
	ESTATUS_FREETYPE_NESTED_FRAME_ACCESS,
	ESTATUS_FREETYPE_INVALID_FRAME_READ,

	ESTATUS_FREETYPE_RASTER_UNINITIALIZED,
	ESTATUS_FREETYPE_RASTER_CORRUPTED,
	ESTATUS_FREETYPE_RASTER_OVERFLOW,
	ESTATUS_FREETYPE_RASTER_NEGATIVE_HEIGHT,

	ESTATUS_FREETYPE_TOO_MANY_CACHES,

	ESTATUS_FREETYPE_INVALID_OPCODE,
	ESTATUS_FREETYPE_TOO_FEW_ARGUMENTS,
	ESTATUS_FREETYPE_STACK_OVERFLOW,
	ESTATUS_FREETYPE_CODE_OVERFLOW,
	ESTATUS_FREETYPE_BAD_ARGUMENT,
	ESTATUS_FREETYPE_DIVIDE_BY_ZERO,
	ESTATUS_FREETYPE_INVALID_REFERENCE,
	ESTATUS_FREETYPE_DEBUG_OPCODE,
	ESTATUS_FREETYPE_ENDF_IN_EXEC_STREAM,
	ESTATUS_FREETYPE_NESTED_DEFS,
	ESTATUS_FREETYPE_INVALID_CODERANGE,
	ESTATUS_FREETYPE_EXECUTION_TOO_LONG,
	ESTATUS_FREETYPE_TOO_MANY_FUNCTION_DEFS,
	ESTATUS_FREETYPE_TOO_MANY_INSTRUCTION_DEFS,
	ESTATUS_FREETYPE_TABLE_MISSING,
	ESTATUS_FREETYPE_HORIZ_HEADER_MISSING,
	ESTATUS_FREETYPE_LOCATIONS_MISSING,
	ESTATUS_FREETYPE_NAME_TABLE_MISSING,
	ESTATUS_FREETYPE_CMAP_TABLE_MISSING,
	ESTATUS_FREETYPE_HMTX_TABLE_MISSING,
	ESTATUS_FREETYPE_POST_TABLE_MISSING,
	ESTATUS_FREETYPE_INVALID_HORIZ_METRICS,
	ESTATUS_FREETYPE_INVALID_CHARMAP_FORMAT,
	ESTATUS_FREETYPE_INVALID_PPEM,
	ESTATUS_FREETYPE_INVALID_VER_METRICS,
	ESTATUS_FREETYPE_COULD_NOT_FOUND_CONTEXT,
	ESTATUS_FREETYPE_INVALID_POST_TABLE_FORMAT,
	ESTATUS_FREETYPE_INVALID_POST_TABLE,

	ESTATUS_FREETYPE_SYNTAX_ERROR,
	ESTATUS_FREETYPE_STACK_UNDERFLOW,
	ESTATUS_FREETYPE_IGNORE,

	ESTATUS_FREETYPE_MISSING_STARTFONT_FIELD,
	ESTATUS_FREETYPE_MISSING_FONT_FIELD,
	ESTATUS_FREETYPE_MISSING_SIZE_FIELD,
	ESTATUS_FREETYPE_MISSING_CHARS_FIELD,
	ESTATUS_FREETYPE_MISSING_STARTCHAR_FIELD,
	ESTATUS_FREETYPE_MISSING_ENCODING_FIELD,
	ESTATUS_FREETYPE_MISSING_BBX_FIELD,
	ESTATUS_FREETYPE_BBX_TOO_BIG,
	ESTATUS_FREETYPE_CORRUPTED_FONT_HEADER,
	ESTATUS_FREETYPE_CORRUPTED_FONT_GLYPHS,

	ESTATUS_FREETYPE_UNKNOWN_ERROR,

	// 4700
	ESTATUS_UI_UNKNOWN_CONTROL_TYPE=4700,
	ESTATUS_UI_CONTROL_NOT_REGISTERED,
	ESTATUS_UI_CONTROL_NOT_HIT,
	ESTATUS_UI_NO_AXIS,
	ESTATUS_UI_TOO_SMALL,
	ESTATUS_UI_TRACK_LENGTH_EXCEEDS_TRACK_SIZE,
	ESTATUS_UI_ITEM_NOT_FOUND,
	ESTATUS_UI_UNHANDLED,
	ESTATUS_UI_IMAGE_MISSING,
	ESTATUS_UI_ALREADY_ASSIGNED,
	ESTATUS_UI_CHILD_ALREADY_HAS_PARENT,

	// 4800
	ESTATUS_MODP_RESULTCODE_INVALID_COMMAND = 4800,
	ESTATUS_MODP_RESULTCODE_INVALID_PAYLOAD_LENGTH,
	ESTATUS_MODP_RESULTCODE_BAD_SEQUENCE,
	ESTATUS_MODP_RESULTCODE_TRAIN_IN_PROGRESS,
	ESTATUS_MODP_RESULTCODE_DEVICE_FAULT,
	ESTATUS_MODP_RESULTCODE_COIL_OVER_TEMPERATURE,
	ESTATUS_MODP_RESULTCODE_NO_TRAIN_SEQUENCE,
	ESTATUS_MODP_RESULTCODE_NO_COIL_PRESENT,
	ESTATUS_MODP_RESULTCODE_COIL_FAULT,
	ESTATUS_MODP_RESULTCODE_TIMING_FIELDS_INVALID,
	ESTATUS_MODP_RESULTCODE_UNSUPPORTED_UNKNOWN_COIL,

	// 4900

	// End, leave this here
	ESTATUS_END_OF_STATUS=0x7fffffff
} EStatus;

// Client types
typedef enum
{
	ECLIENT_NOT_SET,					// Client not set
	ECLIENT_SERVER,						// Server app
	ECLIENT_STIM,						// Stimulation app
	ECLIENT_ADMIN,						// Admin application
	ECLIENT_SWUPDATE,					// Software update
	ECLIENT_STIMBOT,					// StomBot app
	ECLIENT_INSPECTOR,					// Inspector app
	ECLIENT_REPORTBOT,					// ReportBot app
	ECLIENT_REPORTAL,					// Reportal app
	ECLIENT_STIMMAGPRO,					// StimMagPro app
	ECLIENT_STIMNEUROSOFT,				// StimNeurosoft app
	ECLIENT_ZAPSTIM,					// ZapStim app
	ECLIENT_EEG,						// EEG app
	ECLIENT_STIMMODP,					// StimModP app
	ECLIENT_STIMMAGSTIM,				// StimMagStim app
	ECLIENT_STIMAPOLLO,					// StimApollo app
} EClientTypes;

// Countries
typedef enum
{
	ECOUNTRY_NOT_SPECIFIED=0,
	ECOUNTRY_AFGHANISTAN=1,
	ECOUNTRY_AKROTIRI=2,
	ECOUNTRY_ALBANIA=3,
	ECOUNTRY_ALGERIA=4,
	ECOUNTRY_AMERICAN_SAMOA=5,
	ECOUNTRY_ANDORRA=6,
	ECOUNTRY_ANGOLA=7,
	ECOUNTRY_ANGUILLA=8,
	ECOUNTRY_ANTARCTICA=9,
	ECOUNTRY_ANTIGUA_AND_BARBUDA=10,
	ECOUNTRY_ARGENTINA=11,
	ECOUNTRY_ARMENIA=12,
	ECOUNTRY_ARUBA=13,
	ECOUNTRY_ASHMORE_AND_CARTIER_ISLANDS=14,
	ECOUNTRY_AUSTRALIA=15,
	ECOUNTRY_AUSTRIA=16,
	ECOUNTRY_AZERBAIJAN=17,
	ECOUNTRY_BAHAMAS_THE=18,
	ECOUNTRY_BAHRAIN=19,
	ECOUNTRY_BANGLADESH=20,
	ECOUNTRY_BARBADOS=21,
	ECOUNTRY_BASSAS_DA_INDIA=22,
	ECOUNTRY_BELARUS=23,
	ECOUNTRY_BELGIUM=24,
	ECOUNTRY_BELIZE=25,
	ECOUNTRY_BENIN=26,
	ECOUNTRY_BERMUDA=27,
	ECOUNTRY_BHUTAN=28,
	ECOUNTRY_BOLIVIA=29,
	ECOUNTRY_BOSNIA_AND_HERZEGOVINA=30,
	ECOUNTRY_BOTSWANA=31,
	ECOUNTRY_BOUVET_ISLAND=32,
	ECOUNTRY_BRAZIL=33,
	ECOUNTRY_BRITISH_INDIAN_OCEAN_TERRITORY=34,
	ECOUNTRY_BRITISH_VIRGIN_ISLANDS=35,
	ECOUNTRY_BRUNEI=36,
	ECOUNTRY_BULGARIA=37,
	ECOUNTRY_BURKINA_FASO=38,
	ECOUNTRY_BURMA=39,
	ECOUNTRY_BURUNDI=40,
	ECOUNTRY_CAMBODIA=41,
	ECOUNTRY_CAMEROON=42,
	ECOUNTRY_CANADA=43,
	ECOUNTRY_CAPE_VERDE=44,
	ECOUNTRY_CAYMAN_ISLANDS=45,
	ECOUNTRY_CENTRAL_AFRICAN_REPUBLIC=46,
	ECOUNTRY_CHAD=47,
	ECOUNTRY_CHILE=48,
	ECOUNTRY_CHINA=49,
	ECOUNTRY_CHRISTMAS_ISLAND=50,
	ECOUNTRY_CLIPPERTON_ISLAND=51,
	ECOUNTRY_COCOS_KEELING_ISLANDS=52,
	ECOUNTRY_COLOMBIA=53,
	ECOUNTRY_COMOROS=54,
	ECOUNTRY_CONGO_DEMOCRATIC_REPUBLIC_OF_THE=55,
	ECOUNTRY_CONGO_REPUBLIC_OF_THE=56,
	ECOUNTRY_COOK_ISLANDS=57,
	ECOUNTRY_CORAL_SEA_ISLANDS=58,
	ECOUNTRY_COSTA_RICA=59,
	ECOUNTRY_COTE_DIVOIRE=60,
	ECOUNTRY_CROATIA=61,
	ECOUNTRY_CUBA=62,
	ECOUNTRY_CYPRUS=63,
	ECOUNTRY_CZECH_REPUBLIC=64,
	ECOUNTRY_DENMARK=65,
	ECOUNTRY_DHEKELIA=66,
	ECOUNTRY_DJIBOUTI=67,
	ECOUNTRY_DOMINICA=68,
	ECOUNTRY_DOMINICAN_REPUBLIC=69,
	ECOUNTRY_ECUADOR=70,
	ECOUNTRY_EGYPT=71,
	ECOUNTRY_EL_SALVADOR=72,
	ECOUNTRY_EQUATORIAL_GUINEA=73,
	ECOUNTRY_ERITREA=74,
	ECOUNTRY_ESTONIA=75,
	ECOUNTRY_ETHIOPIA=76,
	ECOUNTRY_EUROPA_ISLAND=77,
	ECOUNTRY_FALKLAND_ISLANDS_ISLAS_MALVINAS=78,
	ECOUNTRY_FAROE_ISLANDS=79,
	ECOUNTRY_FIJI=80,
	ECOUNTRY_FINLAND=81,
	ECOUNTRY_FRANCE=82,
	ECOUNTRY_FRENCH_GUIANA=83,
	ECOUNTRY_FRENCH_POLYNESIA=84,
	ECOUNTRY_FRENCH_SOUTHERN_AND_ANTARCTIC_LANDS=85,
	ECOUNTRY_GABON=86,
	ECOUNTRY_GAMBIA_THE=87,
	ECOUNTRY_GAZA_STRIP=88,
	ECOUNTRY_GEORGIA=89,
	ECOUNTRY_GERMANY=90,
	ECOUNTRY_GHANA=91,
	ECOUNTRY_GIBRALTAR=92,
	ECOUNTRY_GLORIOSO_ISLANDS=93,
	ECOUNTRY_GREECE=94,
	ECOUNTRY_GREENLAND=95,
	ECOUNTRY_GRENADA=96,
	ECOUNTRY_GUADELOUPE=97,
	ECOUNTRY_GUAM=98,
	ECOUNTRY_GUATEMALA=99,
	ECOUNTRY_GUERNSEY=100,
	ECOUNTRY_GUINEA=101,
	ECOUNTRY_GUINEA_BISSAU=102,
	ECOUNTRY_GUYANA=103,
	ECOUNTRY_HAITI=104,
	ECOUNTRY_HEARD_ISLAND_AND_MCDONALD_ISLANDS=105,
	ECOUNTRY_HOLY_SEE_VATICAN_CITY=106,
	ECOUNTRY_HONDURAS=107,
	ECOUNTRY_HONG_KONG=108,
	ECOUNTRY_HUNGARY=109,
	ECOUNTRY_ICELAND=110,
	ECOUNTRY_INDIA=111,
	ECOUNTRY_INDONESIA=112,
	ECOUNTRY_IRAN=113,
	ECOUNTRY_IRAQ=114,
	ECOUNTRY_IRELAND=115,
	ECOUNTRY_ISLE_OF_MAN=116,
	ECOUNTRY_ISRAEL=117,
	ECOUNTRY_ITALY=118,
	ECOUNTRY_JAMAICA=119,
	ECOUNTRY_JAN_MAYEN=120,
	ECOUNTRY_JAPAN=121,
	ECOUNTRY_JERSEY=122,
	ECOUNTRY_JORDAN=123,
	ECOUNTRY_JUAN_DE_NOVA_ISLAND=124,
	ECOUNTRY_KAZAKHSTAN=125,
	ECOUNTRY_KENYA=126,
	ECOUNTRY_KIRIBATI=127,
	ECOUNTRY_KOREA_NORTH=128,
	ECOUNTRY_KOREA_SOUTH=129,
	ECOUNTRY_KUWAIT=130,
	ECOUNTRY_KYRGYZSTAN=131,
	ECOUNTRY_LAOS=132,
	ECOUNTRY_LATVIA=133,
	ECOUNTRY_LEBANON=134,
	ECOUNTRY_LESOTHO=135,
	ECOUNTRY_LIBERIA=136,
	ECOUNTRY_LIBYA=137,
	ECOUNTRY_LIECHTENSTEIN=138,
	ECOUNTRY_LITHUANIA=139,
	ECOUNTRY_LUXEMBOURG=140,
	ECOUNTRY_MACAU=141,
	ECOUNTRY_MACEDONIA=142,
	ECOUNTRY_MADAGASCAR=143,
	ECOUNTRY_MALAWI=144,
	ECOUNTRY_MALAYSIA=145,
	ECOUNTRY_MALDIVES=146,
	ECOUNTRY_MALI=147,
	ECOUNTRY_MALTA=148,
	ECOUNTRY_MARSHALL_ISLANDS=149,
	ECOUNTRY_MARTINIQUE=150,
	ECOUNTRY_MAURITANIA=151,
	ECOUNTRY_MAURITIUS=152,
	ECOUNTRY_MAYOTTE=153,
	ECOUNTRY_MEXICO=154,
	ECOUNTRY_MICRONESIA_FEDERATED_STATES_OF=155,
	ECOUNTRY_MOLDOVA=156,
	ECOUNTRY_MONACO=157,
	ECOUNTRY_MONGOLIA=158,
	ECOUNTRY_MONTSERRAT=159,
	ECOUNTRY_MOROCCO=160,
	ECOUNTRY_MOZAMBIQUE=161,
	ECOUNTRY_NAMIBIA=162,
	ECOUNTRY_NAURU=163,
	ECOUNTRY_NAVASSA_ISLAND=164,
	ECOUNTRY_NEPAL=165,
	ECOUNTRY_NETHERLANDS=166,
	ECOUNTRY_NETHERLANDS_ANTILLES=167,
	ECOUNTRY_NEW_CALEDONIA=168,
	ECOUNTRY_NEW_ZEALAND=169,
	ECOUNTRY_NICARAGUA=170,
	ECOUNTRY_NIGER=171,
	ECOUNTRY_NIGERIA=172,
	ECOUNTRY_NIUE=173,
	ECOUNTRY_NORFOLK_ISLAND=174,
	ECOUNTRY_NORTHERN_MARIANA_ISLANDS=175,
	ECOUNTRY_NORWAY=176,
	ECOUNTRY_OMAN=177,
	ECOUNTRY_PAKISTAN=178,
	ECOUNTRY_PALAU=179,
	ECOUNTRY_PANAMA=180,
	ECOUNTRY_PAPUA_NEW_GUINEA=181,
	ECOUNTRY_PARACEL_ISLANDS=182,
	ECOUNTRY_PARAGUAY=183,
	ECOUNTRY_PERU=184,
	ECOUNTRY_PHILIPPINES=185,
	ECOUNTRY_PITCAIRN_ISLANDS=186,
	ECOUNTRY_POLAND=187,
	ECOUNTRY_PORTUGAL=188,
	ECOUNTRY_PUERTO_RICO=189,
	ECOUNTRY_QATAR=190,
	ECOUNTRY_REUNION=191,
	ECOUNTRY_ROMANIA=192,
	ECOUNTRY_RUSSIA=193,
	ECOUNTRY_RWANDA=194,
	ECOUNTRY_SAINT_HELENA=195,
	ECOUNTRY_SAINT_KITTS_AND_NEVIS=196,
	ECOUNTRY_SAINT_LUCIA=197,
	ECOUNTRY_SAINT_PIERRE_AND_MIQUELON=198,
	ECOUNTRY_SAINT_VINCENT_AND_THE_GRENADINES=199,
	ECOUNTRY_SAMOA=200,
	ECOUNTRY_SAN_MARINO=201,
	ECOUNTRY_SAO_TOME_AND_PRINCIPE=202,
	ECOUNTRY_SAUDI_ARABIA=203,
	ECOUNTRY_SENEGAL=204,
	ECOUNTRY_SERBIA_AND_MONTENEGRO=205,
	ECOUNTRY_SEYCHELLES=206,
	ECOUNTRY_SIERRA_LEONE=207,
	ECOUNTRY_SINGAPORE=208,
	ECOUNTRY_SLOVAKIA=209,
	ECOUNTRY_SLOVENIA=210,
	ECOUNTRY_SOLOMON_ISLANDS=211,
	ECOUNTRY_SOMALIA=212,
	ECOUNTRY_SOUTH_AFRICA=213,
	ECOUNTRY_SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS=214,
	ECOUNTRY_SPAIN=215,
	ECOUNTRY_SPRATLY_ISLANDS=216,
	ECOUNTRY_SRI_LANKA=217,
	ECOUNTRY_SUDAN=218,
	ECOUNTRY_SURINAME=219,
	ECOUNTRY_SVALBARD=220,
	ECOUNTRY_SWAZILAND=221,
	ECOUNTRY_SWEDEN=222,
	ECOUNTRY_SWITZERLAND=223,
	ECOUNTRY_SYRIA=224,
	ECOUNTRY_TAIWAN=225,
	ECOUNTRY_TAJIKISTAN=226,
	ECOUNTRY_TANZANIA=227,
	ECOUNTRY_THAILAND=228,
	ECOUNTRY_TIMOR_LESTE=229,
	ECOUNTRY_TOGO=230,
	ECOUNTRY_TOKELAU=231,
	ECOUNTRY_TONGA=232,
	ECOUNTRY_TRINIDAD_AND_TOBAGO=233,
	ECOUNTRY_TROMELIN_ISLAND=234,
	ECOUNTRY_TUNISIA=235,
	ECOUNTRY_TURKEY=236,
	ECOUNTRY_TURKMENISTAN=237,
	ECOUNTRY_TURKS_AND_CAICOS_ISLANDS=238,
	ECOUNTRY_TUVALU=239,
	ECOUNTRY_UGANDA=240,
	ECOUNTRY_UKRAINE=241,
	ECOUNTRY_UNITED_ARAB_EMIRATES=242,
	ECOUNTRY_UNITED_KINGDOM=243,
	ECOUNTRY_UNITED_STATES_OF_AMERICA=244,
	ECOUNTRY_URUGUAY=245,
	ECOUNTRY_UZBEKISTAN=246,
	ECOUNTRY_VANUATU=247,
	ECOUNTRY_VENEZUELA=248,
	ECOUNTRY_VIETNAM=249,
	ECOUNTRY_VIRGIN_ISLANDS=250,
	ECOUNTRY_WAKE_ISLAND=251,
	ECOUNTRY_WALLIS_AND_FUTUNA=252,
	ECOUNTRY_WEST_BANK=253,
	ECOUNTRY_WESTERN_SAHARA=254,
	ECOUNTRY_YEMEN=255,
	ECOUNTRY_ZAMBIA=256,
	ECOUNTRY_ZIMBABWE=257,

	ECOUNTRY_COUNT
} ECountry;

#endif
